//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PpMod.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PpMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dick_png {
            get {
                object obj = ResourceManager.GetObject("dick.png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {&quot;VertexArray&quot;: [{&quot;x&quot;: 0.194463, &quot;y&quot;: 0.227294, &quot;z&quot;: -0.069289}, {&quot;x&quot;: 0.174422, &quot;y&quot;: 0.056648, &quot;z&quot;: 0.034901}, {&quot;x&quot;: 0.129935, &quot;y&quot;: 0.260562, &quot;z&quot;: -0.124579}, {&quot;x&quot;: 0.156976, &quot;y&quot;: 0.042425, &quot;z&quot;: 0.064279}, {&quot;x&quot;: 0.133497, &quot;y&quot;: 0.029959, &quot;z&quot;: 0.090029}, {&quot;x&quot;: 0.156976, &quot;y&quot;: 0.042425, &quot;z&quot;: 0.064279}, {&quot;x&quot;: 0.072248, &quot;y&quot;: 0.012126, &quot;z&quot;: 0.126865}, {&quot;x&quot;: 0.104888, &quot;y&quot;: 0.019728, &quot;z&quot;: 0.111162}, {&quot;x&quot;: 0.0, &quot;y&quot;: 0.005864, &quot;z&quot;: 0.1398}, {&quot;x&quot;: 0.219546, &quot;y&quot;: 0.32983, &quot;z&quot;: 0.510144}, {&quot;x&quot;: 0.0, &quot;y&quot;: 0.170394, &quot;z&quot;:  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string dick_txt {
            get {
                return ResourceManager.GetString("dick.txt", resourceCulture);
            }
        }
    }
}
